services:
  mongodb:
    container_name: lavamusic-mongodb
    # higher versions don't work on Apple Silicon
    image: "bitnami/mongodb:4.4"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: 127.0.0.1
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_USER: mongoadmin
      MONGODB_ROOT_PASSWORD: mongopassword
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    restart: on-failure
    volumes:
      - mongodb_data:/data/db
  lavalink:
    container_name: lavamusic-lavalink
    image: ghcr.io/lavalink-devs/lavalink
    environment:
      SERVER_PORT: 2333
      SERVER_ADDRESS: 0.0.0.0
      LAVALINK_SERVER_PASSWORD: "youshallnotpass"
      LAVALINK_SERVER_SOURCES_YOUTUBE: "true"
      LAVALINK_SERVER_SOURCES_BANDCAMP: "true"
      LAVALINK_SERVER_SOURCES_SOUNDCLOUD: "true"
      LAVALINK_SERVER_SOURCES_TWITCH: "true"
      LAVALINK_SERVER_SOURCES_VIMEO: "true"
      LAVALINK_SERVER_SOURCES_HTTP: "true"
      LAVALINK_SERVER_SOURCES_LOCAL: "false"
      LAVALINK_SERVER_BUFFER_DURATION_MS: 400
      LAVALINK_SERVER_FRAME_BUFFER_DURATIONS_MS: 5000
      LAVALINK_SERVER_TRACK_STRUCK_THRESHOLD_MS: 10000
      LAVALINK_SERVER_YOUTUBE_PLAYLIST_LOAD_LIMIT: 6
      LAVALINK_SERVER_PLAYER_UPDATE_INTERVAL: 5
      LAVALINK_SERVER_YOUTUBE_SEARCH_ENABLED: "true"
      LAVALINK_SERVER_SOUNDCLOUD_SEARCH_ENABLED: "true"
      #LAVALINK_SERVER_YOUTUBE_CONFIG_EMAIL:
      #LAVALINK_SERVER_YOUTUBE_CONFIG_PASSWORD:
      LAVALINK_SERVER_SENTRY_DSN: ""
    volumes:
      - ./plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    restart: on-failure
  lavamusic:
    container_name: lavamusic-lavalink
    image: ghcr.io/brblacky/lavamusic:main
    environment:
      TOKEN: "your bot token" # Your bot token
      PREFIX: "your bot prefix" # Your bot prefix
      OWNER_IDS: "your id" # Your id
      CLIENT_ID: "your bot id" # Your bot id
      GUILD_ID: "" # Your server Id if you want to use the for single server
      PRODUCTION: "true" # true for production
      SEARCH_ENGINE: "ytsearch" # ytsearch, scsearch or ytmsearch
      MAX_PLAYLIST_SIZE: "100" # Max playlist size
      MAX_QUEUE_SIZE: "100" # Max queue size
      DATABASE_URL: "mongodb://mongoadmin:mongopassword@mongodb/lavamusic?authSource=admin&directConnection=true" # Your mongodb url
      LAVALINK_URL: "lavalink:2333" # Your lavalink url
      LAVALINK_AUTH: "youshallnotpass" # Your lavalink password
      LAVALINK_NAME: "Blacky" # Your lavalink name
      LAVALINK_SECURE: "false" # true if you are using https
    restart: on-failure
    depends_on:
      - lavalink
      - mongodb
volumes:
  mongodb_data:
